feat: publish gmc updates to connections
Health-Education-England/tis-revalidation-connection pull request #136
Opened 2021-06-16 09:53 UTC by CaiWillis

2021-06-16 11:08 UTC, jayanta2018 requested changes

2021-06-16 11:08 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/connection/config/ElasticsearchConfig.java
> +package uk.nhs.hee.tis.revalidation.connection.config;
Looks like it's a new class. Need to put MIT licence here.

2021-06-16 11:08 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/GmcDoctor.java
> +package uk.nhs.hee.tis.revalidation.connection.entity;
MIT Licence

2021-06-16 11:08 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/connection/message/receiver/ConnectionMessageReceiver.java
> +package uk.nhs.hee.tis.revalidation.connection.message.receiver;
MIT Licence

2021-06-16 11:08 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/connection/message/receiver/GmcDoctorMessageReceiver.java
> +package uk.nhs.hee.tis.revalidation.connection.message.receiver;
Same here, MIT

2021-06-16 11:08 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/connection/message/receiver/MessageReceiver.java
> +package uk.nhs.hee.tis.revalidation.connection.message.receiver;
MIT

2021-06-16 11:08 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/connection/message/receiver/SyncMessageReceiver.java
> +package uk.nhs.hee.tis.revalidation.connection.message.receiver;
MIT

2021-06-16 11:08 UTC, jayanta2018 commented on src/test/java/uk/nhs/hee/tis/revalidation/connection/message/receiver/ConnectionMessageReceiverTest.java
> +package uk.nhs.hee.tis.revalidation.connection.message.receiver;
MIT

2021-06-16 11:08 UTC, jayanta2018 commented on src/test/java/uk/nhs/hee/tis/revalidation/connection/message/receiver/GmcDoctorMessageReceiverTest.java
> +package uk.nhs.hee.tis.revalidation.connection.message.receiver;
MIT

2021-06-16 11:08 UTC, jayanta2018 commented on src/test/java/uk/nhs/hee/tis/revalidation/connection/message/receiver/SyncMessageReceiverTest.java
> +package uk.nhs.hee.tis.revalidation.connection.message.receiver;
MIT

2021-06-16 11:08 UTC, jayanta2018 commented on src/test/java/uk/nhs/hee/tis/revalidation/connection/message/receiver/SyncMessageReceiverTest.java
> +//  @Test
Test annontation is commented out here?

2021-06-16 11:29 UTC, jayanta2018 submitted a review, later dismissed
LGTM now

2021-06-16 11:33 UTC, DorisWongNHS submitted a review, later dismissed

2021-06-17 15:08 UTC, DorisWongNHS approved these changes

2021-06-17 15:10 UTC, merged