feat: remove extremely inefficient getMaster ES sync setup
Health-Education-England/tis-revalidation-connection pull request #212
Opened 2022-12-22 12:14 UTC by CaiWillis

TIS21-3775: Remove legacy steps 6 and 7 from code and rabbit config

2022-12-22 12:17 UTC, CaiWillis commented
There is more code in the MasterElasticSearchService that should be removed as the CDC renders it redundant, but in the interests of avoiding scope creep, it's best covered when we come to implement the add/remove connections functionality to which it is related

2022-12-29 13:31 UTC, hihilary requested changes

2022-12-29 13:31 UTC, hihilary commented on src/main/resources/application.yml
> -    reval.routingKey.indexrebuildgetmastercommand.requested: ${REVAL_RABBIT_INDEX_REBUILD_GETMASTER_ROUTING_KEY:reval.indexrebuildgetmastercommand.requested}
The queue and routing key are also used in the RabbitConfig file.

2023-01-04 13:27 UTC, hihilary approved these changes

2023-01-05 11:43 UTC, merged