chore: remove unused field connectionStatus
Health-Education-England/tis-revalidation-connection pull request #213
Opened 2023-03-16 10:58 UTC by CaiWillis

TIS21-4194: TCS, Integration Service & Connection Service - Remove field connectionStatus

2023-03-16 16:16 UTC, JosephKelly requested changes
You got off lightly in otherways... I don't mind fixing up those assertions to be actual test assertions rather than java `assert`ions

2023-03-30 12:56 UTC, hihilary approved these changes

2023-04-05 10:00 UTC, JosephKelly requested changes
Oh. Just one more thing.

2023-04-05 10:00 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticSearchIndexUpdateHelperTest.java
> -    assertThat(returnedView.getConnectionStatus(), is(CONNECTED));
Looks like this and other constants are no longer needed in this test.  Might as well clean those up too.

2023-04-05 10:52 UTC, JosephKelly approved these changes

2023-04-05 10:59 UTC, merged