feat: restrict discrepancies list to admin's DBCs matching in TCS or GMC
Health-Education-England/tis-revalidation-connection pull request #226
Opened 2023-06-07 12:43 UTC by CaiWillis

TIS21-4633: Reval Connections MVP: Restrict Discrepancies list by Designated Body

2023-06-07 14:39 UTC, CaiWillis commented
Some notes:

- We already pass the Admin's DBCs from the front end for this endpoint
- The es query can roughly be read as:
`NOT Military
AND
   (
      param 1 matches designatedBody 
      OR 
      param 1 matches tcsDesignatedBody
   )
AND
   (
      param 0 matches doctorFirstName
      OR
      param 0 matches doctorLastName
      OR
      param 0 matches gmcNumber
   )`

2023-06-08 10:23 UTC, hihilary commented
Had a Postman test on my local, the dbc search query works.

However, I've just noticed `DiscrepanciesElasticSearchService` and `ConnectedElasticSearchService` look very similar, but one throws a RuntimeException, the other throws a self-defined exception. And I'm also wondering if it's worth refactoring these 2 services to reuse the same `searchForPage` method.

2023-06-08 10:31 UTC, hihilary approved these changes
I have questions in the previous comment. The PR itself looks good to me.

2023-06-08 10:33 UTC, CaiWillis commented
> Had a Postman test on my local, the dbc search query works.
> 
> However, I've just noticed `DiscrepanciesElasticSearchService` and `ConnectedElasticSearchService` look very similar, but one throws a RuntimeException, the other throws a self-defined exception. And I'm also wondering if it's worth refactoring these 2 services to reuse the same `searchForPage` method.

Yep I'll sort the exceptions out to make everything tidy, and will have a think about them using the same method. I think to begin with they looked very different but have become similar, so it's whether they're likely to be different again

2023-06-08 10:40 UTC, JosephKelly reviewed
I think the practice of making Util classes `final` isn't as essential but still has value in declaring intent

2023-06-08 10:40 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticsearchQueryHelper.java
> +    List<String> escapedCodes = new ArrayList<>();
If you have some spare time, you might get a kick out of using a java stream from `designatedBodyCodes`, with map and "joining" collector, to make this redundant.

2023-06-08 10:40 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticsearchQueryHelper.java
> +public class ElasticsearchQueryHelper {
As a Util class, we should mark it as `final`

2023-06-08 10:40 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticsearchQueryHelperTest.java
Is there value in having test of empty & null values and values without `1-`?

2023-06-08 11:41 UTC, CaiWillis commented on src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticsearchQueryHelperTest.java
I don't think so(?) The method will be passed a list of strings from the front end, if there was something weird in that list like List.of("validString", "", null "") then something else has gone wrong

2023-06-08 12:43 UTC, JosephKelly requested changes
Minor tweaks that shouldn't affect it passing.

2023-06-08 12:43 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/connection/service/DiscrepanciesElasticSearchServiceTest.java
> +    final String formattedDbcs = "1rsspz7 1rssq1b";
You should define this once in the class.

2023-06-08 12:43 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/connection/service/DiscrepanciesElasticSearchServiceTest.java
> +    final String formattedDbcs = "1rsspz7 1rssq1b";
You should define these once in the class.

2023-06-08 13:46 UTC, JosephKelly approved these changes
Minor tweaks that shouldn't affect it passing.

2023-06-08 13:46 UTC, merged