fix: update submission date when adding a new connection
Health-Education-England/tis-revalidation-connection pull request #236
Opened 2023-09-27 12:30 UTC by CaiWillis

TIS21-5015: Update submission date using gmc tryadddoctor response data when connecting a doctor

2023-09-28 10:46 UTC, CaiWillis commented
> Does this do what it says on the tin? Initiated by an unhappiness at the use of a `java.util.Date`, I went looking for where `GmcConnectionResponseDto.submissionDate` is populated.

Just going by what is already used for the response object from GMC client 🤷 Otherwise:
Disconnect: set submission date to null
Connect: update submission date

2023-09-28 14:08 UTC, JosephKelly requested changes
Much nicer! There are a couple of things I'd like you to look at.

2023-09-29 09:25 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/connection/service/GmcClientServiceTest.java
> +        submissionDate.getMonthValue(), submissionDate.getYear());
You can use a formatter here if you don't want to do use a fixed date on L#88.

2023-09-29 09:26 UTC, JosephKelly approved these changes

2023-09-29 09:49 UTC, merged