feat: added connection exception logic when trainee current dbc does …
Health-Education-England/tis-revalidation-connection pull request #59
Opened 2021-01-25 15:51 UTC by jayanta2018

…not match with programme owner dbc TIS21-1072

2021-01-26 15:31 UTC, DorisWongNHS commented
Just had a quick look at why the Sonar check is failing, seems there are two issues you may want to look at:
- there are 6 code smells in the new commited code
- test for ExceptionService is needed for the test coverage

2021-01-26 15:40 UTC, DorisWongNHS requested changes
Just had a quick look at why the Sonar check is failing, seems there are two issues you may want to look at:

- there are 6 code smells in the new commited code
- test for ExceptionService is needed for the test coverage

2021-01-26 16:47 UTC, jayanta2018 commented
> Just had a quick look at why the Sonar check is failing, seems there are two issues you may want to look at:
> 
> * there are 6 code smells in the new commited code
> * test for ExceptionService is needed for the test coverage

Thanks @DorisWongNHS I have taken care of those issues

2021-01-29 15:59 UTC, DorisWongNHS approved these changes

2021-02-01 15:14 UTC, merged